# Generated by Django 2.1.3 on 2018-11-18 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_classified', '0003_auto_20180717_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('NEW', 'NEW'), ('PROCESSED', 'PROCESSED'), ('INVALIDATED', 'INVALIDATED')], max_length=255)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='django_classified.Item')),
            ],
        ),
    ]
